name: emotiary
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.2.1+1
  get: ^4.6.5

  fluttertoast: ^8.0.9
  flutter_svg: ^0.23.0+1
  extended_image: ^6.1.0
  lottie: ^1.4.3

  card_swiper: ^2.0.4


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lotties/

  fonts:
    - family: suit
      fonts:
        - asset: assets/fonts/SUIT-Heavy.otf
          weight: 900
        - asset: assets/fonts/SUIT-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/SUIT-Bold.otf
          weight: 700
        - asset: assets/fonts/SUIT-SemiBold.otf
          weight: 600
        - asset: assets/fonts/SUIT-Medium.otf
          weight: 500
        - asset: assets/fonts/SUIT-Regular.otf
          weight: 400
        - asset: assets/fonts/SUIT-Light.otf
          weight: 300
        - asset: assets/fonts/SUIT-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/SUIT-Thin.otf
          weight: 100
    - family: korailRoundGothic
      fonts:
        - asset: assets/fonts/Korail_Round_Gothic_Bold.ttf
          weight: 700
        - asset: assets/fonts/Korail_Round_Gothic_Medium.ttf
          weight: 500
        - asset: assets/fonts/Korail_Round_Gothic_Light.ttf
          weight: 300
    - family: kyoboHandWriting
      fonts:
        - asset: assets/fonts/KyoboHandwriting2021sjy.otf
          weight: 700